config/routes.rb
require 'sidekiq/web'

ILikeYouReally::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    resources :comments
    resources :activities
  end
  root to: "main#index"

  resources :facebook do
    collection do
      get :friends, path: "/choose/friends"
      post :add_friends
      put :toggle_like
      put :toggle_comment
    end
  end
  resources :facebook_guest do
    collection do
      get :friends
    end
  end

  resources :dashboards, path: "dashboard", only: [:index] do
    collection do
      get :details
    end
  end

  put "/wizard/:wizard_name/hide" => "wizards#hide", as: "hide_wizard"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  validates :value, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = current_user.comments
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to comments_path, notice: "Created!"
    else
      render "new"
    end
  end

  def show
    @comment = current_user.comments.find(params[:id])
  end

  def edit
    @comment = current_user.comments.find(params[:id])
  end

  def update
    @comment = current_user.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to comment_path(@comment), notice: "Updated!"
    else
      render "edit"
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    if @comment.destroy
      redirect_to comments_path, notice: "Removed!"
    else
      redirect_to comment_path(@comment), alert: "Try again!"
    end
  end


private
  def comment_params
    params.require(:comment)
      .permit(:value)
  end
end

app/views/comments/edit.html.erb
<div class="container">
  <h2>Edit Comment</h2>

  <%= form_for @comment, class:"form-horizontal", role:"form" do |f| %>
  <div class="form-group">
    <%= f.label "Message", class:"col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :value, class:"form-control"%>
    </div>
  </div>
  <br/>
  <br/>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Save", class: "btn btn-default" %>
    </div>
    <% end %>
  </div>

<%= link_to "Back", comments_path%>

app/views/comments/index.html.erb
<%= help_message_for "comments" %>

<div class="container">
 <br/>
<table class="table">
  <tr>
    <td>Comment</td>
    <td></td>
  </tr>
  <% @comments.each do |comment| %>
  <tr>
    <td><%= link_to comment.value, comment_path(comment)%></td>
    <td>
      <%= link_to "Edit", edit_comment_path(comment)%>
      |
      <%= link_to "Remove", comment_path(comment), method: :delete %>
    </td>
  </tr>
  <% end %>
</table>

<%= link_to "New Comment", new_comment_path, class: "btn btn-primary btn-lg"%>
<%= link_to "Dashboard", dashboards_path%>
</div>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_for @comment do |f| %>

<p>
<%= f.label "Message"%><br/>
<%= f.text_field :value%><br/>
<%= f.submit "Save" %>
<p>

<% end %>

app/views/comments/show.html.erb
<div class="container">
  <h2>Comment</h2>
<table class="table table-bordered">
  <tr>
    <td><%= @comment.value%></td>
  </tr>
</table>

<%= link_to "Edit", edit_comment_path(@comment) %> |
<%= link_to "Comments", comments_path %>

</div>