config/routes.rb
require 'sidekiq/web'

ILikeYouReally::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    resources :comments
    resources :activities
  end
  root to: "main#index"

  resources :facebook do
    collection do
      get :friends, path: "/choose/friends"
      post :add_friends
      put :toggle_like
      put :toggle_comment
    end
  end
  resources :facebook_guest do
    collection do
      get :friends
    end
  end

  resources :dashboards, path: "dashboard", only: [:index] do
    collection do
      get :details
    end
  end

  put "/wizard/:wizard_name/hide" => "wizards#hide", as: "hide_wizard"
end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController

  def friends
    @raw_friends = FacebookFriends.new(current_user).update_graph
      .relationships
      .joins(:facebook_user)
      .order("facebook_users.name")
      .page(params[:page])
      .per(50)

    unless params[:filter].blank?
      @raw_friends = @raw_friends.fuzzy_search(facebook_users: {
                                                 name: params[:filter]
                                               })
    end

    @friends = @raw_friends.map { |f| RelationshipDecorator.new(f) }

    respond_to do |format|
      format.html
      format.js
    end
  end

  def add_friends
    current_user.update_attributes(user_params)
    redirect_to root_path
  end

  def toggle_like
    @relationship = current_user.relationships.where(facebook_user_id: params[:facebook_user_id]).first
    @relationship.like = !@relationship.like
    @relationship.save
    respond_to do |format|
      format.js
    end
  end

  def toggle_comment
    @relationship = current_user.relationships.where(facebook_user_id: params[:facebook_user_id]).first
    @relationship.comment = !@relationship.comment
    @relationship.save
    respond_to do |format|
      format.js
    end
  end

private
  def user_params
    params.require(:user)
      .permit(relationships_attributes: [:like, :comment, :facebook_user_id])
  end
end

app/helpers/facebook_helper.rb
module FacebookHelper
  PREPOSITIONS = %w(of van von de da do)
  def friend_name(friend)
    first, *middle, last = friend.name.split
    middle_initials = middle.map { |name|
      if PREPOSITIONS.member?(name.downcase)
        name
      else
        "#{name[0]}."
      end
    }.join(" ")

    "#{first} #{middle_initials} #{last}"
  end

  def cycle_stat_message
    message = t("user").keys.sample
    t("user.#{message}")
  end

  def facebook_image_uri(uid, width = 80, height = 80)
    "https://graph.facebook.com/#{uid}/picture?width=#{width}&height=#{height}"
  end
end

app/views/facebook/_friend.html.erb
<%= cache(relationship.friend) do %>
<div class="friend-data">
  <div class="avatar">
    <img src="<%= relationship.image %>">
  </div>

  <span class="friend-name">
    <a href="https://www.facebook.com/<%= relationship.facebook_id %>" target= "_blank"><%= friend_name relationship %></a>
  </span>
</div>
<% end %>

app/views/facebook/_friends.html.erb
<% friends.each_with_index do |friend, current| %>
  <%= render partial: "relationship", object: friend, locals: { current: current } %>    
<% end %>

<%= paginate @raw_friends, filter: params[:filter] %>

app/views/facebook/_relationship.html.erb
<%= cache(relationship) do %>
<div class="col-md-3 cols-xs-4 friend">
  <div class="background" style="background: url(<%= relationship.image(200, 200) %>); background-size: 100% auto;">
  </div>
  <div class="foreground">
    <div class="actions">
      <%= hidden_field_tag "user[relationships_attributes][#{current}][facebook_user_id]", relationship.facebook_id  %>
      <%= link_to toggle_like_facebook_index_path(facebook_user_id: relationship.facebook_id), class: "like", remote: true, method: :put do %>
      <i class="<%= relationship.like_class %> check" data-checkbox="user[relationships_attributes][<%= current %>][like]"></i>
      <% end %>
      <%= link_to toggle_comment_facebook_index_path(facebook_user_id: relationship.facebook_id), class: "comment", remote: true, method: :put do %>
      <i class="<%= relationship.comment_class %> check" data-checkbox="user[relationships_attributes][<%= current %>][comment]"></i>
      <% end %>
    </div>

    <div class="friend-name">
      <a href="https://www.facebook.com/<%= relationship.facebook_id %>" target= "_blank"><%= friend_name relationship %></a>
    </div>      
  </div>
</div>
<% end %>

app/views/facebook/_stats.html.erb
<% cache(cache_key_for_latest_stats_update) do %>
<div class="page-header">
  <h1>You</h1>  
</div>

<div class="stats">
  <%= image_tag "#{current_user.facebook_image_uri}?width=300&height=300", class: "you" %>

  <ul class="latest nav">
    <li class="happy">
      <%= (cycle_stat_message % ["<span class='count'>#{current_user.happy_friends_count}</span>", "person".pluralize(current_user.happy_friends_count)]).html_safe %>
    </li>
  </ul>
</div>
<% end %>

app/views/facebook/friends.html.erb
<%= help_message_for "friends" %>

<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="page-header">
        <h1>Friends</h1>  
      </div>

      <%= form_tag friends_facebook_index_path, class: "filtering", remote: true, method: :get do %>
        <label for="filter">
          <%= t("filter.label") %>
        </label>
        <%= text_field_tag :filter, params[:filter], class: "form-control", placeholder: t("filter.placeholder") %>
      <% end %>

      <div class="friends">
        <%= render partial: "friends", object: @friends %>
      </div>
    </div>

    <div class="col-md-3 stats-container">
      <%= render partial: "stats" %>
    </div>    
  </div>
</div>

<script type="text/javascript">
  var scheduledFetchId,
      form = $("form.filtering");

  function startSearch() {
    $(".friends").spin();
  }
  
  function endSearch() {
    $(".friends").spin(false);
  }

  function showSpinners() {
    $(this).parents(".friend").spin();
  }

  function hideSpinners() {
    $(this).parents(".friend").spin(false);
  }

  $(document).ready(function() {
    $(".friends").infinitescroll({
      navSelector: ".pagination",
      nextSelector: ".pagination .next a",
      itemSelector: ".friends .friend",
      msgText: "<em>Loading more of your beautiful friends...</em>",
      finishedMessage: "<em>These are all you've got. Enjoy them.</em>"
    });

  
    $(".like, .comment")
      .on("ajax:before", showSpinners)
      .on("ajax:complete", hideSpinners);


    form.on("ajax:before", startSearch);
    form.on("ajax:complete", endSearch);
  
    $("input[name='filter']").on("keyup", function() {
      var currentVal = $(this).val(),
          form = $(this).parents("form");

      if (currentVal.length == 0 || currentVal.length >= 3) {
        if (scheduledFetchId) {
          clearTimeout(scheduledFetchId);
          scheduledFetchId = null;
        }

        scheduledFetchId = Filter.scheduleFiltering(form, currentVal);
      }
    });
  });
</script>

app/views/facebook/friends.js.erb
$(".friends").html("<%= j(render(partial: "friends", object: @friends)) %>");

app/views/facebook/toggle_comment.js.erb
<% if @relationship.comment? %>
   $(".comment[href$='<%= @relationship.facebook_user_id %>'] i").removeClass("icon-comments-alt").addClass("icon-comments");
<% else %>
    $(".comment[href$='<%= @relationship.facebook_user_id %>'] i").removeClass("icon-comments").addClass("icon-comments-alt");
<% end %>

$(".stats-container").html("<%= j(render(partial: "stats")) %>");

app/views/facebook/toggle_like.js.erb
<% if @relationship.like? %>
   $(".like[href$='<%= @relationship.facebook_user_id %>'] i").removeClass("icon-thumbs-up-alt").addClass("icon-thumbs-up");
<% else %>
    $(".like[href$='<%= @relationship.facebook_user_id %>'] i").removeClass("icon-thumbs-up").addClass("icon-thumbs-up-alt");
<% end %>

$(".stats-container").html("<%= j(render(partial: "stats")) %>");