config/routes.rb
require 'sidekiq/web'

ILikeYouReally::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    resources :comments
    resources :activities
  end
  root to: "main#index"

  resources :facebook do
    collection do
      get :friends, path: "/choose/friends"
      post :add_friends
      put :toggle_like
      put :toggle_comment
    end
  end
  resources :facebook_guest do
    collection do
      get :friends
    end
  end

  resources :dashboards, path: "dashboard", only: [:index] do
    collection do
      get :details
    end
  end

  put "/wizard/:wizard_name/hide" => "wizards#hide", as: "hide_wizard"
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
  def hide
    wizard_name = params[:wizard_name]
    current_user.hidden_wizards.where(wizard_name: wizard_name).first_or_create

    respond_to do |format|
      format.js
    end
  end
end

app/views/wizards/_choose_friends.html.erb
<div class="container wizard">
  <div class="row">
    <div class="grid-md-12 grid-xs-12">
      <div class="">
        <h2>Setting up</h2>
      </div>
      
      <p class="lead">
        Ok, you're ready to start. If everything went well, you're seeing a list of your friends below. Now it's time to help us work our magic: click on the little <i class="icon-thumbs-up-alt icon"></i> to indicate you want to automatically like some of that friend's posts; <i class="icon-comments-alt icon"></i> will give you similar behavior for comments.
      </p>
      
      <p class="lead">
        When you're ready to write your personal generic comments (an oxymoron for the social media age), click on "Next Step". They are optional, though, so feel free to stop here.
      </p>
      
      <div class="actions pull-right">
        <%= link_to "Don't show this again", hide_wizard_path(wizard_name: "friends"), remote: true, method: :put %>
        
        <%= link_to comments_path do %>
          <button class="btn btn-primary">
            Next Step
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/wizards/_comments.html.erb
<div class="container wizard">
  <div class="row">
    <div class="grid-md-12 grid-xs-12">
      <div class="">
        <h2>What will this do?</h2>
      </div>
      
      <p class="lead">
        The concept is simple: you write a few very generic text options, and we'll sample from them when the time comes. Think of things that could fit most situations, like 'Wow!', or 'Great!', or ':)'. Emoticons are good for their multiple meanings, as they can be read ironically or earnestly.
      </p>
      <p class="lead">
        If it seems like too much trouble, just skip this step and we won't comment on anything.
      </p>

      <div class="actions pull-right">
        <%= link_to "Don't show this again", hide_wizard_path(wizard_name: "comments"), remote: true, method: :put %>
      </div>
    </div>
  </div>
</div>

app/views/wizards/_dashboard.html.erb
<div class="container wizard">
  <div class="row">
    <div class="grid-md-12 grid-xs-12">
      <h2>What is this?</h2>
      
      <p class="lead">
        What you see below is a summary of what the application has done for you and your friends. At any time in the future you can come here and enjoy all the bliss you've spread among your network.
      </p>

      <div class="actions pull-right">
        <%= link_to "Don't show this again", hide_wizard_path(wizard_name: "dashboard"), remote: true, method: :put %>

      </div>
    </div>
  </div>
</div>

app/views/wizards/_friends.html.erb
<div class="container wizard">
  <div class="row">
    <div class="grid-md-12 grid-xs-12">
      <div class="">
        <h2>Setting up</h2>
      </div>
      
      <p class="lead">
        Ok, you're ready to start. If everything went well, you're seeing a list of your friends below. Now it's time to help us work our magic: click on the little <i class="icon-thumbs-up-alt icon"></i> to indicate you want to automatically like some of that friend's posts; <i class="icon-comments-alt icon"></i> will give you similar behavior for comments.
      </p>
      
      <p class="lead">
        When you're ready to write your personal generic comments (an oxymoron for the social media age), click on "Next Step". They are optional, though, so feel free to stop here.
      </p>
      
      <div class="actions pull-right">
        <%= link_to "Don't show this again", hide_wizard_path(wizard_name: "friends"), remote: true, method: :put %>
        
        <%= link_to comments_path do %>
          <button class="btn btn-primary">
            Next Step
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/wizards/_write_comments.html.erb
<div class="container wizard">
  <div class="row">
    <div class="grid-md-12 grid-xs-12">
      <div class="">
        <h2>What will this do?</h2>
      </div>
      
      <p class="lead">
        The concept is simple: you write a few very generic text options, and we'll sample from them when the time comes. Think of things that could fit most situations, like 'Wow!', or 'Great!', or ':)'. Emoticons are good for their multiple meanings, as they can be read ironically or earnestly.
      </p>
      <p class="lead">
        If it seems like too much trouble, just skip this step and we won't comment on anything.
      </p>

      <div class="actions pull-right">
        <%= link_to "Don't show this again", hide_wizard_path(wizard_name: "comments"), remote: true, method: :put %>
      </div>
    </div>
  </div>
</div>

app/views/wizards/hide.js.erb
$(".wizard").hide(500);