config/routes.rb
require 'sidekiq/web'

ILikeYouReally::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    resources :comments
    resources :activities
  end
  root to: "main#index"

  resources :facebook do
    collection do
      get :friends, path: "/choose/friends"
      post :add_friends
      put :toggle_like
      put :toggle_comment
    end
  end
  resources :facebook_guest do
    collection do
      get :friends
    end
  end

  resources :dashboards, path: "dashboard", only: [:index] do
    collection do
      get :details
    end
  end

  put "/wizard/:wizard_name/hide" => "wizards#hide", as: "hide_wizard"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I Like You, Really</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body class="logged-in">
  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to friends_facebook_index_path, class: "navbar-brand" do %>
        <i class="icon-thumbs-up-alt"></i> I Like You, Really
      <% end %>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="align-menu"><%= link_to t("menu.dashboard"), dashboards_path %></li>
        <li class="align-menu"><%= link_to t("menu.friends"), friends_facebook_index_path %></li>
        <li class="align-menu"><%= link_to t("menu.comments"), comments_path %></li>
        <li class="align-menu"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <li class="align-menu">
          <%= image_tag current_user.facebook_image_uri, class: "user-avatar" %>
        </li>
      </ul>
    </div>
  </nav>

  <%= yield %>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I Like You, Really</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="logged-out">
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_url, class: "navbar-brand" do %>
          <i class="icon-thumbs-up-alt"></i> I Like You, Really
        <% end %>
      </div>

      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to user_omniauth_authorize_path(:facebook) do %>
              <button class="btn btn-facebook"><i class="icon-facebook"></i> | Connect with Facebook</button>
            <% end %>
          </li>
          <li>
            <%= link_to friends_facebook_guest_index_path do %>
              <button class="btn btn-pinterest">Login as Guest</button>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>    
  </body>
</html>